--- @class ghapi.Releases.Assets
--- @field url string
--- @field name string
--- @field size number
--- @field download_count number
--- @field updated_at string
--- @field browser_download_url string
---- @field id string
---- @field node_id string
---- @field label string?
---- @field uploader any
---- @field content_type string
---- @field state string
---- @field digest string
---- @field created_at string

--- @class ghapi.Releases
--- @field url string
--- @field tag_name string
--- @field name string
--- @field draft boolean
--- @field prerelease boolean
--- @field updated_at string
--- @field zipball_url string
--- @field assets ghapi.Releases.Assets[]
---- @field id string
---- @field upload_url string
---- @field html_url string
---- @field node_id string
---- @field target_committish string
---- @field tarball_url string
---- @field body string
---- @field reactions any
---- @field mentions_count number
---- @field immutable boolean
---- @field created_at string
---- @field published_at string
---- @field assets_url string
---- @field author any

--- @class ghapi.Ratelimit.Entry
--- @field limit number
--- @field remaining number
--- @field reset number
--- @field used number
--- @field resource string

--- @class ghapi.Ratelimit.Resources
--- @field code_search ghapi.Ratelimit.Entry
--- @field core ghapi.Ratelimit.Entry
--- @field graphql ghapi.Ratelimit.Entry
--- @field integration_manifest ghapi.Ratelimit.Entry
--- @field search ghapi.Ratelimit.Entry

--- @class ghapi.Ratelimit
--- @field resources ghapi.Ratelimit.Resources
--- @field rate ghapi.Ratelimit.Entry