--- @meta imm

--- @class imm.ParsedConfig: { [string]: string }
--- Determines what mod to load at the next loading.\
--- The entry is mod ID and version separated by `=` (includes surrounding whitespaces).\
--- The list is separated by `==` (includes surrounding whitespaces).\
--- e.g. `Steamodded=1.0.0~beta-0827c == Cryptid=0.5.12a`
---
--- Changes won't be applied with the next restart.
---
--- Useful for when Balatro crashes at loading and it disables all mods.
--- This config can be used to re-enable all disabled mods during loading crash.
--- @field nextEnable? string
---
--- If present, dissable mod colors from badges.
--- @field disableModColor? string
---
--- If present, logs debug output.
--- @field debug? string
---
--- Allows users to specify the GitHub API token
--- @field githubToken? string
---
--- If `ignore`, disables imm from handling early crash entirely. \
--- If `nodisable`, only list installed mods
--- @field handleEarlyError? string
---
--- Maximum HTTPS threads. Defaults to 6.
--- @field httpsThreads? string
---
--- Maximum concurrent tasks. Defaults to 4.
--- Currently only used for number of downloads at once.
--- @field concurrentTasks? string
---
--- Maximum concurrent tasks for modpacks. Defaults to 4.
--- Currently only used for number of downloads at once.
--- @field mpConcurrentTasks? string
---
--- If present, disables safety warning after everytime the manager is open.
--- @field disableSafetyWarning? string
---
--- If present, disables flavor text after everytime the manager is open.
--- @field disableFlavor? string
---
--- If present, disallows updating a mod that does from latest commit if the mod does not have any release.
--- @field noUpdateUnreleasedMods? string
---
--- If present, disallows downloading a mod dependency from latest commit if the mod does not have any release.
--- @field noAutoDownloadUnreleasedMods? string
---
--- If present, forces using curl bindings to do HTTPS request.
--- @field enforceCurl? string
---
--- If null, shows a popup player for the first time installation,
--- The popup is only shown when there's no other mods installed
--- @field init? string
---

--- @type imm.Base
local c
return c
